### ISSUE TITLE
你好~ 能问下你atom里面用的右侧页面代码预览的滚动的插件是什么吗?

### ISSUE THREAD

**Issue by aemoe** [jobn123/atom-sticker#1]
就是右边类似于sublime text的滚动条 一直没找到呢~

**Comment by ghost** [comment]
标签页把萌妹纸挡住了

![image](https://cloud.githubusercontent.com/assets/8049878/22052896/67fc0fb6-dd88-11e6-8cb1-50f25eb95ef2.png)

没打开标签页时，萌妹纸出来了

![image](https://cloud.githubusercontent.com/assets/8049878/22052997/d789aa32-dd88-11e6-90d8-d28827488d48.png)

**Comment by jobn123** [comment]
@aemoe  minimap

**Comment by goodluckforever** [comment]
请问适用于mac吗，我按完control+alt+s也还是没有用呢

**Comment by tsukino17** [comment]
的确是，标签页把妹子挡住了

**Comment by jobn123** [comment]
@goodluckforever @liuliangsir  刚才给插件升级了，麻烦你们升级下。

**Comment by aemoe** [comment]
@jobn123 感谢~
