### ISSUE TITLE
并没有很萌好嘛~

### ISSUE THREAD

**Issue by w550** [jobn123/atom-sticker#2]

**Comment by jobn123** [comment]
@w550 可以自定义图片

**Comment by myronliu347** [comment]
@jobn123  怎么换图片

**Comment by jobn123** [comment]
@myronliu347  现在换图片的方式还很丑露，以后要优化

* package 面板里面找到 atom-sticker 点击一下
* 然后再点一下 View code
* 找到 styles 目录下的 atom-sticker.less
* 替换less文件里面的 background url
* 替换完要 ctrl + alt + cmd + l
