### ISSUE TITLE
Hey! ) How i can change or/and append new stickers in pack? 

### ISSUE THREAD

**Issue by alexTitakoff** [jobn123/atom-sticker#4]
Hello man.
Sorry, i dont undestand oriental typografy ;) and you may be already response on this question.

How i can append pic`s in you plugin?

ooo!. And also, how i can change or define   sizes of pic`s? 

Thanks :)

**Comment by krakowdeveloper** [comment]
You can not change the image sticker with this pack.

**Comment by jobn123** [comment]
Sorry, it does not support automatic replacement of images, you need to manually set it

* First in the package panel to find atom-sticker click, then  click View code

* Find the atom-sticker.less under the styles directory

* Replace less background url inside the file

* when finished   ctrl + alt + cmd + l

**Comment by hyprhare** [comment]
Can't we modify the code to read from either a local or a remote directory? 
Or at the least we can certainly modify the code to change from using a single image url, to using an array for multiple urls, which can then be picked via a cycle or at random; yes?
